const ACTIVATION = "ACTIVATION";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGOUT_FAILED = "LOGIN_FAILED";
const HANDLE_LOADING = "HANDLE_LOADING";

const TYPE = {
    ACTIVATION: ACTIVATION,
    LOGIN: LOGIN,
    LOGOUT: LOGOUT,
    LOGIN_FAILED: LOGIN_FAILED,
    LOGOUT_FAILED: LOGOUT_FAILED,
    HANDLE_LOADING: HANDLE_LOADING
}

export default TYPE;