const ACTIVATION = "ACTIVATION";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGIN_WITH_FORM_ERROR = "LOGIN_WITH_FORM_EROR";
const HANDLE_LOADING = "HANDLE_LOADING";

const TYPE = {
    ACTIVATION: ACTIVATION,
    LOGIN: LOGIN,
    LOGOUT: LOGOUT,
    LOGIN_FAILED: LOGIN_FAILED,
    LOGIN_WITH_FORM_ERROR : LOGIN_WITH_FORM_ERROR,
    HANDLE_LOADING: HANDLE_LOADING,
}

export default TYPE;