const HANDLE_LOADING = "HANDLE_LOADING";
//Authentication
const ACTIVATION = "ACTIVATION";
const LOGIN = "LOGIN";
const LOGOUT = "LOGOUT";
const LOGIN_FAILED = "LOGIN_FAILED";
const LOGOUT_FAILED = "LOGIN_FAILED";
//Order
const NEED_RESPONSE = "NEED_RESPONSE";
const NEED_PURCHASE = "NEED_PURCHASE";
const PURCHASED     = "PURCHASED";
const READY_TO_SHIP = "READY_TO_SHIP";
const SHIPPED       = "SHIPPED";


const TYPE = {
    ACTIVATION     : ACTIVATION,
    LOGIN          : LOGIN,
    LOGOUT         : LOGOUT,
    LOGIN_FAILED   : LOGIN_FAILED,
    LOGOUT_FAILED  : LOGOUT_FAILED,
    HANDLE_LOADING : HANDLE_LOADING,
    NEED_RESPONSE  : NEED_RESPONSE ,
    NEED_PURCHASE  : NEED_PURCHASE ,
    PURCHASED      : PURCHASED     ,
    READY_TO_SHIP  : READY_TO_SHIP ,
    SHIPPED        : SHIPPED       
}

export default TYPE;