const LOGIN = '/login';
const DASHBOARD = `/dashboard`;
const PRODUCT = `/product`;
const PRODUCT_CREATE = `${PRODUCT}/create`;
const PRODUCT_EDIT = `${PRODUCT}/edit`;
const ORDER = `/order`;
const ORDER_CANCLE = `${ORDER}/cancle`;
const ORDER_COMPLETED = `${ORDER}/completed`;
const CUSTOMER = `/customer`;
const CUSTOMER_GROUPS = `${CUSTOMER}/groups`
const SUPPLIER = `/supplier`;
const QUESTION_ANSWER = `/questions-answer`;
const QUESTION_ANSWER_DETAIL = `${QUESTION_ANSWER}/:id`;


const PATH_URL = {
    LOGIN: LOGIN,
    DASHBOARD: DASHBOARD,
    PRODUCT: PRODUCT,
    PRODUCT_CREATE: PRODUCT_CREATE,
    PRODUCT_EDIT: PRODUCT_EDIT,
    QUESTION_ANSWER: QUESTION_ANSWER,
    ORDER: ORDER,
    ORDER_CANCLE: ORDER_CANCLE,
    ORDER_COMPLETED: ORDER_COMPLETED,
    CUSTOMER: CUSTOMER,
    CUSTOMER_GROUPS: CUSTOMER_GROUPS,
    SUPPLIER: SUPPLIER,
    QUESTION_ANSWER_DETAIL: QUESTION_ANSWER_DETAIL

}

export default PATH_URL;