const LOGIN = '/login';
const HOME = '/';
const DASHBOARD_CHINA = '/dashboard-china';
const DASHBOARD_MENU_CHINA = `${DASHBOARD_CHINA}/:menu`;
const DASHBOARD_MENU_TAB_CHINA = `${DASHBOARD_CHINA}/:menu/:tab`;
const DASHBOARD_INDONESIA = '/dashboard-indonesia';
const DASHBOARD_MENU_INDONESIA = `${DASHBOARD_INDONESIA}/:menu`;
const DASHBOARD_MENU_TAB_INDONESIA = `${DASHBOARD_INDONESIA}/:menu/:tab`;

const PATH_URL = {
    LOGIN: LOGIN,
    HOME: HOME,
    DASHBOARD_CHINA: DASHBOARD_CHINA,
    DASHBOARD_MENU_CHINA: DASHBOARD_MENU_CHINA,
    DASHBOARD_MENU_TAB_CHINA: DASHBOARD_MENU_TAB_CHINA,
    DASHBOARD_INDONESIA: DASHBOARD_INDONESIA,
    DASHBOARD_MENU_INDONESIA: DASHBOARD_MENU_INDONESIA,
    DASHBOARD_MENU_TAB_INDONESIA: DASHBOARD_MENU_TAB_INDONESIA
}

export default PATH_URL;