const GET_BY_ID_QUESTION_ANSWER = 'question-answer/product'
const GET_QUESTION_ANSWER = 'question-answer'
export const PATH_QUESTION_ANSWER = {
    GET_QUESTION_ANSWER : GET_QUESTION_ANSWER,
    GET_BY_ID_QUESTION_ANSWER: GET_BY_ID_QUESTION_ANSWER
}